# Generated by Django 5.1 on 2024-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_admin_employee_password_employee_tc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='tc_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tc_id',
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
