# Generated by Django 5.1 on 2024-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_address_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
