# Generated by Django 5.1 on 2024-08-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_customaddress_employee_custom_address_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAddress',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='custom_address_value',
        ),
    ]
